image: node:latest
stages:
  - build
cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - ls
    - npm install ./greet1
  artifacts:
    paths:
    - node_modules/