image: docker:19.03.1
stages:
  - build
services:
  - docker:19.03.1-dind
before_script:
  - docker info
build_containers:
  stage: build
  image: docker:19.03.1
  script:
    - cd ./greet2
    - docker build .
    - cd ../greet1
    - docker build .
      