image: node:latest
stages:
  - build
  - test
cache:
  paths:
    - ./greet1/node_modules/
    - ./greet2/node_modules/

install_dependencies:
  stage: build
  script:
    - cd ./greet1
    - npm install
    - cd ../greet2
    - npm install
  artifacts:
    paths:
      - ./greet1/node_modules/
      - ./greet2/node_modules/

test_application:
  stage: test
  script: 
    - cd ./greet2
    - npm test