image: node:latest
stages:
  - build
cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - ls
    - cd greet1/
    - npm install
  artifacts:
    paths:
    - node_modules/